version: "3.7"
services:
  web:
    image: go-clean-architecture
    container_name: go-container
    ports:
      - 8080:8080
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./config.json:/config.json

  postgresql:
    image: postgres:alpine3.20
    container_name: go-clean-architecture-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=go_full
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
