### GET request to root
GET localhost:8080/

###

# curl -X POST --location "http://localhost:8080/user/create"
POST localhost:8080/user/create
Content-Type: application/json

{
  "name": "wcn",
  "phone": "0895402275040",
  "gender": 1,
  "email": "wcn@gmmail.com",
  "password": "P@ssw0rd"
}

###

